name: Build library check

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.yml'
      - '**/Makefile'
      - '**/.bat'
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Download OpenOrbis Toolchain
      run: |
        curl -sL https://github.com/illusion0001/OpenOrbis-PS4-Toolchain/releases/latest/download/toolchain.tar.gz | tar xz -C ./
        sudo apt install llvm lld
        echo "OO_PS4_TOOLCHAIN=$GITHUB_WORKSPACE/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV

    - name: Build SDK Lib
      run: |
        clang -v
        make DEBUGFLAGS=1
        make PRINTF=1
        make DEBUGFLAGS=1 PRINTF=1
        make clean
        make install
        echo "GOLDHEN_SDK=$GITHUB_WORKSPACE/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV
        zip -r /home/runner/sdk.zip /home/runner/work/GoldHEN_Plugins_SDK/GoldHEN_Plugins_SDK/OpenOrbis
    
    -  name: Upload a Build Artifact
       uses: actions/upload-artifact@v4.3.1
       with: 
        name: GoldHen
    # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/sdk.zip
    # The desired behavior if no files are found using the provided path.

          
        
        

      
